steps:
  - id: "Prepare Cloud Build workspace"
    name: docker.io/bbhuston/gcloud-make:392.0.0-alpine
    dir: /workspace
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        set -e
        echo '-------------------------------------------------------------------------------------'
        echo
        echo 	Checking your Cloud Build workspace...
        echo
        echo '-------------------------------------------------------------------------------------'
        sleep 1s
        cd /workspace && ls -lah /workspace
        ############################################################################################
        cat << EOF > make_env
        PROJECT_ID=${_PROJECT_ID}
        ORGANIZATION_ID=${_ORGANIZATION_ID}
        BILLING_ACCOUNT_ID=${_BILLING_ACCOUNT_ID}
        GOOGLE_ADMIN_DOMAIN=${_GOOGLE_ADMIN_DOMAIN}
        GCP_SUPER_USER=${_GCP_SUPER_USER}
        EOF
        ############################################################################################
        cat make_env
  - id: "Assign super-user permissions"
    name: docker.io/bbhuston/gcloud-make:392.0.0-alpine
    dir: /workspace
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        set -e
        make -s assign-super-user-permissions
    waitFor: ["Prepare Cloud Build workspace"]
  - id: "Create Google Identity Groups"
    name: docker.io/bbhuston/gcloud-make:392.0.0-alpine
    dir: /workspace
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        set -e
        make -s create-google-identity-groups
    waitFor: ["Assign super-user permissions"]
  - id: "Assign super-user group permissions"
    name: docker.io/bbhuston/gcloud-make:392.0.0-alpine
    dir: /workspace
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        set -e
        make -s assign-super-user-group-permissions
    waitFor: ["Create Google Identity Groups"]
  - id: "Prepare GCP environment"
    name: docker.io/bbhuston/gcloud-make:392.0.0-alpine
    dir: /workspace
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        set -e
        make -s prepare-gcp-environment
    waitFor: ["Assign super-user group permissions"]
  - id: "Uninstall blueprints"
    name: docker.io/bbhuston/gcloud-make:392.0.0-alpine
    dir: /workspace
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        set -e
        make -s uninstall-blueprints
    waitFor: ["Prepare GCP environment"]
  - id: "Delete Config Controller"
    name: docker.io/bbhuston/gcloud-make:392.0.0-alpine
    dir: /workspace
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        set -e
        make -s delete-config-controller -e OPTIONS=--quiet
    waitFor: ["Uninstall blueprints"] 
  - id: "Delete GCP project"
    name: docker.io/bbhuston/gcloud-make:392.0.0-alpine
    dir: /workspace
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        set -e
        make -s delete-gcp-project -e OPTIONS=--quiet
    waitFor: ["Delete Config Controller"] 
# Set timeout equal to 133 minutes
timeout: 8000s
substitutions:
  _PROJECT_ID: my-project-id
  _ORGANIZATION_ID: my-organization-id
  _BILLING_ACCOUNT_ID: my-billing-account-id
  _GOOGLE_ADMIN_DOMAIN: my-google-admin-domain
  _GCP_SUPER_USER: my-gcp-super-user